#!/bin/bash
# Runs once at container boot (s6-rc oneshot). Two jobs:
#   1. Prepare /var/log/claworc and the claworc user's HOME.
#   2. Snapshot PID 1's env to /etc/environment and
#      /etc/profile.d/claworc-env.sh so SSH sessions — which go through
#      PAM and do NOT inherit sshd's env — see the vars passed to
#      `docker run -e` / the Kubernetes pod spec. The shim verbs are exec'd
#      over SSH, so this is what delivers CLAWORC_AGENT_TOKEN,
#      CLAWORC_LLM_PROXY_URL, etc. to them.

set -e

# SSH host keys: regenerate per-pod so every container has unique keys.
if command -v ssh-keygen >/dev/null 2>&1; then
    ssh-keygen -A >/dev/null 2>&1 || true
fi

# ---------------------------------------------------------------------------
# Filesystem + user home
# ---------------------------------------------------------------------------
mkdir -p /var/log/claworc
chmod 755 /var/log/claworc
touch /var/log/claworc/agent.log
chown claworc:claworc /var/log/claworc/agent.log

test -f /home/claworc/.bashrc || cp -a /etc/skel/. /home/claworc/
# Hermes runs each chat turn from this directory (AGENTS.md, file tools,
# git operations all resolve from here). Declared as meta.workspace_dir.
mkdir -p /home/claworc/hermes-workspace
# Shim persistent state (Claworc session-key -> Hermes session-id map)
# lives on the instance PVC.
mkdir -p /home/claworc/.claworc/shim
chown -R claworc:claworc /home/claworc

# Ephemeral shim runtime state (chat PIDs for chat-abort).
mkdir -p /run/claworc/shim
chmod 755 /run/claworc /run/claworc/shim

# ---------------------------------------------------------------------------
# Propagate PID 1 env to PAM and bash login shells
# ---------------------------------------------------------------------------
exclude='^(PATH|HOME|HOSTNAME|TERM|PWD|OLDPWD|SHLVL|SHELL|LOGNAME|USER|MAIL|_)='

: > /etc/environment
printenv | grep -vE "$exclude" | while IFS='=' read -r key value; do
    escaped="${value//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped" >> /etc/environment
done
chmod 644 /etc/environment

{
    echo '# Generated by init-setup.sh at container boot. Do not edit.'
    printenv | grep -vE "$exclude" | while IFS='=' read -r key value; do
        printf 'export %s=%q\n' "$key" "$value"
    done
} > /etc/profile.d/claworc-env.sh
chmod 644 /etc/profile.d/claworc-env.sh
