#!/bin/bash
# Runs once at container boot (s6-rc oneshot). Three jobs:
#   1. Prepare /var/log/claworc and the claworc user's HOME.
#   2. Snapshot PID 1's env to /etc/environment and
#      /etc/profile.d/claworc-env.sh so SSH sessions — which go through
#      PAM and do NOT inherit sshd's env — see the vars passed to
#      `docker run -e` / the Kubernetes pod spec. The shim verbs are exec'd
#      over SSH, so this is what delivers CLAWORC_AGENT_TOKEN,
#      CLAWORC_LLM_PROXY_URL, etc. to them.
#   3. Apply CLAWORC_INITIAL_LLM_CONFIG through the shim's own configure-llm
#      verb so first boot and reconfiguration share one code path.

set -e

# SSH host keys: regenerate per-pod so every container has unique keys.
if command -v ssh-keygen >/dev/null 2>&1; then
    ssh-keygen -A >/dev/null 2>&1 || true
fi

# ---------------------------------------------------------------------------
# Filesystem + user home
# ---------------------------------------------------------------------------
mkdir -p /var/log/claworc
chmod 755 /var/log/claworc
touch /var/log/claworc/agent.log
chown claworc:claworc /var/log/claworc/agent.log

test -f /home/claworc/.bashrc || cp -a /etc/skel/. /home/claworc/
# The NanoClaw agent workspace (files, long-term memory, container.json).
# /workspace/agent inside the image symlinks here so upstream NanoClaw's
# hardcoded group-dir paths keep working on the persistent volume.
mkdir -p /home/claworc/workspace
# Shim persistent state: per-session NanoClaw DB pairs + LLM routing.
mkdir -p /home/claworc/.claworc/shim/nanoclaw/sessions
chown -R claworc:claworc /home/claworc

# Ephemeral shim runtime state (chat/runner PIDs, supervisor heartbeat) —
# written by the claworc-owned supervisor and verbs.
mkdir -p /run/claworc/shim
chown -R claworc:claworc /run/claworc
chmod 755 /run/claworc /run/claworc/shim

# ---------------------------------------------------------------------------
# Propagate PID 1 env to PAM and bash login shells
# ---------------------------------------------------------------------------
exclude='^(PATH|HOME|HOSTNAME|TERM|PWD|OLDPWD|SHLVL|SHELL|LOGNAME|USER|MAIL|_)='

: > /etc/environment
printenv | grep -vE "$exclude" | while IFS='=' read -r key value; do
    escaped="${value//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped" >> /etc/environment
done
chmod 644 /etc/environment

{
    echo '# Generated by init-setup.sh at container boot. Do not edit.'
    printenv | grep -vE "$exclude" | while IFS='=' read -r key value; do
        printf 'export %s=%q\n' "$key" "$value"
    done
} > /etc/profile.d/claworc-env.sh
chmod 644 /etc/profile.d/claworc-env.sh

# ---------------------------------------------------------------------------
# First-boot LLM routing (CLAWORC_INITIAL_LLM_CONFIG, docs/shim.md)
# ---------------------------------------------------------------------------
if [ -n "${CLAWORC_INITIAL_LLM_CONFIG:-}" ]; then
    if ! printf '%s' "$CLAWORC_INITIAL_LLM_CONFIG" | /opt/claworc/shim/configure-llm; then
        echo "configure-llm failed; continuing boot without initial LLM routing" >&2
    fi
fi
